// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env['GOOGLE_API_KEY2'] ?? '',
    appId: '1:1060696718130:web:072d623ed8e2130c26f52b',
    messagingSenderId: '1060696718130',
    projectId: 'all-in-agri',
    authDomain: 'all-in-agri.firebaseapp.com',
    storageBucket: 'all-in-agri.appspot.com',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['GOOGLE_API_KEY1'] ?? '',
    appId: '1:1060696718130:android:6cf4e0cec48337e126f52b',
    messagingSenderId: '1060696718130',
    projectId: 'all-in-agri',
    storageBucket: 'all-in-agri.appspot.com',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['GOOGLE_API_KEY3'] ?? '',
    appId: '1:1060696718130:ios:c00c13330d358d0226f52b',
    messagingSenderId: '1060696718130',
    projectId: 'all-in-agri',
    storageBucket: 'all-in-agri.appspot.com',
    iosBundleId: 'com.example.allinagri',
  );
}
