// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCC05gduJ1JC-1D7V_DMFV8y4E5kDAit00',
    appId: '1:1060696718130:web:072d623ed8e2130c26f52b',
    messagingSenderId: '1060696718130',
    projectId: 'all-in-agri',
    authDomain: 'all-in-agri.firebaseapp.com',
    storageBucket: 'all-in-agri.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCskTPMKHMATcjJ5OXh4j_kLa-pNrxoaBo',
    appId: '1:1060696718130:android:6cf4e0cec48337e126f52b',
    messagingSenderId: '1060696718130',
    projectId: 'all-in-agri',
    storageBucket: 'all-in-agri.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMaFUo_xMj3ASry0gRUBquKo2Il-qCFUY',
    appId: '1:1060696718130:ios:c00c13330d358d0226f52b',
    messagingSenderId: '1060696718130',
    projectId: 'all-in-agri',
    storageBucket: 'all-in-agri.appspot.com',
    iosBundleId: 'com.example.allinagri',
  );

}